package net.minecraft.init;

import net.minecraft.block.Block;
import net.minecraft.block.BlockBeacon;
import net.minecraft.block.BlockBush;
import net.minecraft.block.BlockCactus;
import net.minecraft.block.BlockCauldron;
import net.minecraft.block.BlockChest;
import net.minecraft.block.BlockDaylightDetector;
import net.minecraft.block.BlockDeadBush;
import net.minecraft.block.BlockDoublePlant;
import net.minecraft.block.BlockDynamicLiquid;
import net.minecraft.block.BlockFire;
import net.minecraft.block.BlockFlower;
import net.minecraft.block.BlockGrass;
import net.minecraft.block.BlockHopper;
import net.minecraft.block.BlockLeaves;
import net.minecraft.block.BlockMycelium;
import net.minecraft.block.BlockPistonBase;
import net.minecraft.block.BlockPistonExtension;
import net.minecraft.block.BlockPistonMoving;
import net.minecraft.block.BlockPortal;
import net.minecraft.block.BlockRedstoneComparator;
import net.minecraft.block.BlockRedstoneRepeater;
import net.minecraft.block.BlockRedstoneWire;
import net.minecraft.block.BlockReed;
import net.minecraft.block.BlockSand;
import net.minecraft.block.BlockSkull;
import net.minecraft.block.BlockSlab;
import net.minecraft.block.BlockStainedGlass;
import net.minecraft.block.BlockStainedGlassPane;
import net.minecraft.block.BlockStaticLiquid;
import net.minecraft.block.BlockTallGrass;
import net.minecraft.block.BlockTripWireHook;
import net.minecraft.util.ResourceLocation;

public class Blocks
{
    public static final Block field_150350_a;
    public static final Block field_150348_b;
    public static final BlockGrass field_150349_c;
    public static final Block field_150346_d;
    public static final Block field_150347_e;
    public static final Block field_150344_f;
    public static final Block field_150345_g;
    public static final Block field_150357_h;
    public static final BlockDynamicLiquid field_150358_i;
    public static final BlockStaticLiquid field_150355_j;
    public static final BlockDynamicLiquid field_150356_k;
    public static final BlockStaticLiquid lava;
    public static final BlockSand sand;
    public static final Block field_150351_n;
    public static final Block field_150352_o;
    public static final Block field_150366_p;
    public static final Block field_150365_q;
    public static final Block log;
    public static final Block log2;
    public static final BlockLeaves leaves;
    public static final BlockLeaves leaves2;
    public static final Block sponge;
    public static final Block glass;
    public static final Block field_150369_x;
    public static final Block lapis_block;
    public static final Block field_150367_z;
    public static final Block sandstone;
    public static final Block noteblock;
    public static final Block bed;
    public static final Block golden_rail;
    public static final Block detector_rail;
    public static final BlockPistonBase sticky_piston;
    public static final Block web;
    public static final BlockTallGrass tallgrass;
    public static final BlockDeadBush field_150330_I;
    public static final BlockPistonBase piston;
    public static final BlockPistonExtension piston_head;
    public static final Block field_150325_L;
    public static final BlockPistonMoving piston_extension;
    public static final BlockFlower yellow_flower;
    public static final BlockFlower red_flower;
    public static final BlockBush brown_mushroom;
    public static final BlockBush red_mushroom;
    public static final Block gold_block;
    public static final Block iron_block;
    public static final BlockSlab double_stone_slab;
    public static final BlockSlab stone_slab;
    public static final Block brick_block;
    public static final Block field_150335_W;
    public static final Block bookshelf;
    public static final Block mossy_cobblestone;
    public static final Block field_150343_Z;
    public static final Block torch;
    public static final BlockFire fire;
    public static final Block mob_spawner;
    public static final Block oak_stairs;
    public static final BlockChest field_150486_ae;
    public static final BlockRedstoneWire redstone_wire;
    public static final Block field_150482_ag;
    public static final Block field_150484_ah;
    public static final Block field_150462_ai;
    public static final Block wheat;
    public static final Block farmland;
    public static final Block field_150460_al;
    public static final Block field_150470_am;
    public static final Block standing_sign;
    public static final Block field_180413_ao;
    public static final Block spruce_door;
    public static final Block field_180412_aq;
    public static final Block field_180411_ar;
    public static final Block field_180410_as;
    public static final Block field_180409_at;
    public static final Block ladder;
    public static final Block rail;
    public static final Block stone_stairs;
    public static final Block wall_sign;
    public static final Block field_150442_at;
    public static final Block stone_pressure_plate;
    public static final Block field_150454_av;
    public static final Block wooden_pressure_plate;
    public static final Block field_150450_ax;
    public static final Block field_150439_ay;
    public static final Block unlit_redstone_torch;
    public static final Block redstone_torch;
    public static final Block field_150430_aB;
    public static final Block snow_layer;
    public static final Block ice;
    public static final Block snow;
    public static final BlockCactus cactus;
    public static final Block clay;
    public static final BlockReed reeds;
    public static final Block jukebox;
    public static final Block oak_fence;
    public static final Block spruce_fence;
    public static final Block birch_fence;
    public static final Block jungle_fence;
    public static final Block dark_oak_fence;
    public static final Block acacia_fence;
    public static final Block field_150423_aK;
    public static final Block netherrack;
    public static final Block soul_sand;
    public static final Block glowstone;
    public static final BlockPortal portal;
    public static final Block lit_pumpkin;
    public static final Block cake;
    public static final BlockRedstoneRepeater field_150413_aR;
    public static final BlockRedstoneRepeater field_150416_aS;
    public static final Block field_150415_aT;
    public static final Block monster_egg;
    public static final Block stonebrick;
    public static final Block brown_mushroom_block;
    public static final Block red_mushroom_block;
    public static final Block iron_bars;
    public static final Block glass_pane;
    public static final Block melon_block;
    public static final Block pumpkin_stem;
    public static final Block melon_stem;
    public static final Block vine;
    public static final Block oak_fence_gate;
    public static final Block spruce_fence_gate;
    public static final Block birch_fence_gate;
    public static final Block jungle_fence_gate;
    public static final Block dark_oak_fence_gate;
    public static final Block acacia_fence_gate;
    public static final Block brick_stairs;
    public static final Block stone_brick_stairs;
    public static final BlockMycelium mycelium;
    public static final Block waterlily;
    public static final Block nether_brick;
    public static final Block nether_brick_fence;
    public static final Block nether_brick_stairs;
    public static final Block nether_wart;
    public static final Block field_150381_bn;
    public static final Block field_150382_bo;
    public static final BlockCauldron cauldron;
    public static final Block end_portal;
    public static final Block end_portal_frame;
    public static final Block end_stone;
    public static final Block dragon_egg;
    public static final Block redstone_lamp;
    public static final Block lit_redstone_lamp;
    public static final BlockSlab double_wooden_slab;
    public static final BlockSlab wooden_slab;
    public static final Block cocoa;
    public static final Block sandstone_stairs;
    public static final Block field_150412_bA;
    public static final Block ender_chest;
    public static final BlockTripWireHook tripwire_hook;
    public static final Block tripwire;
    public static final Block emerald_block;
    public static final Block spruce_stairs;
    public static final Block birch_stairs;
    public static final Block jungle_stairs;
    public static final Block command_block;
    public static final BlockBeacon field_150461_bJ;
    public static final Block cobblestone_wall;
    public static final Block flower_pot;
    public static final Block carrots;
    public static final Block potatoes;
    public static final Block field_150471_bO;
    public static final BlockSkull skull;
    public static final Block field_150467_bQ;
    public static final Block field_150447_bR;
    public static final Block light_weighted_pressure_plate;
    public static final Block heavy_weighted_pressure_plate;
    public static final BlockRedstoneComparator field_150441_bU;
    public static final BlockRedstoneComparator field_150455_bV;
    public static final BlockDaylightDetector field_150453_bW;
    public static final BlockDaylightDetector field_180402_cm;
    public static final Block redstone_block;
    public static final Block field_150449_bY;
    public static final BlockHopper field_150438_bZ;
    public static final Block quartz_block;
    public static final Block quartz_stairs;
    public static final Block activator_rail;
    public static final Block field_150409_cd;
    public static final Block field_150406_ce;
    public static final Block field_180401_cv;
    public static final Block field_180400_cw;
    public static final Block hay_block;
    public static final Block carpet;
    public static final Block hardened_clay;
    public static final Block coal_block;
    public static final Block packed_ice;
    public static final Block acacia_stairs;
    public static final Block dark_oak_stairs;
    public static final Block slime_block;
    public static final BlockDoublePlant double_plant;
    public static final BlockStainedGlass field_150399_cn;
    public static final BlockStainedGlassPane stained_glass_pane;
    public static final Block field_180397_cI;
    public static final Block sea_lantern;
    public static final Block standing_banner;
    public static final Block wall_banner;
    public static final Block red_sandstone;
    public static final Block red_sandstone_stairs;
    public static final BlockSlab double_stone_slab2;
    public static final BlockSlab stone_slab2;

    /**
     * Returns the Block in the blockRegistry with the specified name.
     */
    private static Block getRegisteredBlock(String p_180383_0_)
    {
        return Block.field_149771_c.func_82594_a(new ResourceLocation(p_180383_0_));
    }

    static
    {
        if (!Bootstrap.func_179869_a())
        {
            throw new RuntimeException("Accessed Blocks before Bootstrap!");
        }
        else
        {
            field_150350_a = getRegisteredBlock("air");
            field_150348_b = getRegisteredBlock("stone");
            field_150349_c = (BlockGrass)getRegisteredBlock("grass");
            field_150346_d = getRegisteredBlock("dirt");
            field_150347_e = getRegisteredBlock("cobblestone");
            field_150344_f = getRegisteredBlock("planks");
            field_150345_g = getRegisteredBlock("sapling");
            field_150357_h = getRegisteredBlock("bedrock");
            field_150358_i = (BlockDynamicLiquid)getRegisteredBlock("flowing_water");
            field_150355_j = (BlockStaticLiquid)getRegisteredBlock("water");
            field_150356_k = (BlockDynamicLiquid)getRegisteredBlock("flowing_lava");
            lava = (BlockStaticLiquid)getRegisteredBlock("lava");
            sand = (BlockSand)getRegisteredBlock("sand");
            field_150351_n = getRegisteredBlock("gravel");
            field_150352_o = getRegisteredBlock("gold_ore");
            field_150366_p = getRegisteredBlock("iron_ore");
            field_150365_q = getRegisteredBlock("coal_ore");
            log = getRegisteredBlock("log");
            log2 = getRegisteredBlock("log2");
            leaves = (BlockLeaves)getRegisteredBlock("leaves");
            leaves2 = (BlockLeaves)getRegisteredBlock("leaves2");
            sponge = getRegisteredBlock("sponge");
            glass = getRegisteredBlock("glass");
            field_150369_x = getRegisteredBlock("lapis_ore");
            lapis_block = getRegisteredBlock("lapis_block");
            field_150367_z = getRegisteredBlock("dispenser");
            sandstone = getRegisteredBlock("sandstone");
            noteblock = getRegisteredBlock("noteblock");
            bed = getRegisteredBlock("bed");
            golden_rail = getRegisteredBlock("golden_rail");
            detector_rail = getRegisteredBlock("detector_rail");
            sticky_piston = (BlockPistonBase)getRegisteredBlock("sticky_piston");
            web = getRegisteredBlock("web");
            tallgrass = (BlockTallGrass)getRegisteredBlock("tallgrass");
            field_150330_I = (BlockDeadBush)getRegisteredBlock("deadbush");
            piston = (BlockPistonBase)getRegisteredBlock("piston");
            piston_head = (BlockPistonExtension)getRegisteredBlock("piston_head");
            field_150325_L = getRegisteredBlock("wool");
            piston_extension = (BlockPistonMoving)getRegisteredBlock("piston_extension");
            yellow_flower = (BlockFlower)getRegisteredBlock("yellow_flower");
            red_flower = (BlockFlower)getRegisteredBlock("red_flower");
            brown_mushroom = (BlockBush)getRegisteredBlock("brown_mushroom");
            red_mushroom = (BlockBush)getRegisteredBlock("red_mushroom");
            gold_block = getRegisteredBlock("gold_block");
            iron_block = getRegisteredBlock("iron_block");
            double_stone_slab = (BlockSlab)getRegisteredBlock("double_stone_slab");
            stone_slab = (BlockSlab)getRegisteredBlock("stone_slab");
            brick_block = getRegisteredBlock("brick_block");
            field_150335_W = getRegisteredBlock("tnt");
            bookshelf = getRegisteredBlock("bookshelf");
            mossy_cobblestone = getRegisteredBlock("mossy_cobblestone");
            field_150343_Z = getRegisteredBlock("obsidian");
            torch = getRegisteredBlock("torch");
            fire = (BlockFire)getRegisteredBlock("fire");
            mob_spawner = getRegisteredBlock("mob_spawner");
            oak_stairs = getRegisteredBlock("oak_stairs");
            field_150486_ae = (BlockChest)getRegisteredBlock("chest");
            redstone_wire = (BlockRedstoneWire)getRegisteredBlock("redstone_wire");
            field_150482_ag = getRegisteredBlock("diamond_ore");
            field_150484_ah = getRegisteredBlock("diamond_block");
            field_150462_ai = getRegisteredBlock("crafting_table");
            wheat = getRegisteredBlock("wheat");
            farmland = getRegisteredBlock("farmland");
            field_150460_al = getRegisteredBlock("furnace");
            field_150470_am = getRegisteredBlock("lit_furnace");
            standing_sign = getRegisteredBlock("standing_sign");
            field_180413_ao = getRegisteredBlock("wooden_door");
            spruce_door = getRegisteredBlock("spruce_door");
            field_180412_aq = getRegisteredBlock("birch_door");
            field_180411_ar = getRegisteredBlock("jungle_door");
            field_180410_as = getRegisteredBlock("acacia_door");
            field_180409_at = getRegisteredBlock("dark_oak_door");
            ladder = getRegisteredBlock("ladder");
            rail = getRegisteredBlock("rail");
            stone_stairs = getRegisteredBlock("stone_stairs");
            wall_sign = getRegisteredBlock("wall_sign");
            field_150442_at = getRegisteredBlock("lever");
            stone_pressure_plate = getRegisteredBlock("stone_pressure_plate");
            field_150454_av = getRegisteredBlock("iron_door");
            wooden_pressure_plate = getRegisteredBlock("wooden_pressure_plate");
            field_150450_ax = getRegisteredBlock("redstone_ore");
            field_150439_ay = getRegisteredBlock("lit_redstone_ore");
            unlit_redstone_torch = getRegisteredBlock("unlit_redstone_torch");
            redstone_torch = getRegisteredBlock("redstone_torch");
            field_150430_aB = getRegisteredBlock("stone_button");
            snow_layer = getRegisteredBlock("snow_layer");
            ice = getRegisteredBlock("ice");
            snow = getRegisteredBlock("snow");
            cactus = (BlockCactus)getRegisteredBlock("cactus");
            clay = getRegisteredBlock("clay");
            reeds = (BlockReed)getRegisteredBlock("reeds");
            jukebox = getRegisteredBlock("jukebox");
            oak_fence = getRegisteredBlock("fence");
            spruce_fence = getRegisteredBlock("spruce_fence");
            birch_fence = getRegisteredBlock("birch_fence");
            jungle_fence = getRegisteredBlock("jungle_fence");
            dark_oak_fence = getRegisteredBlock("dark_oak_fence");
            acacia_fence = getRegisteredBlock("acacia_fence");
            field_150423_aK = getRegisteredBlock("pumpkin");
            netherrack = getRegisteredBlock("netherrack");
            soul_sand = getRegisteredBlock("soul_sand");
            glowstone = getRegisteredBlock("glowstone");
            portal = (BlockPortal)getRegisteredBlock("portal");
            lit_pumpkin = getRegisteredBlock("lit_pumpkin");
            cake = getRegisteredBlock("cake");
            field_150413_aR = (BlockRedstoneRepeater)getRegisteredBlock("unpowered_repeater");
            field_150416_aS = (BlockRedstoneRepeater)getRegisteredBlock("powered_repeater");
            field_150415_aT = getRegisteredBlock("trapdoor");
            monster_egg = getRegisteredBlock("monster_egg");
            stonebrick = getRegisteredBlock("stonebrick");
            brown_mushroom_block = getRegisteredBlock("brown_mushroom_block");
            red_mushroom_block = getRegisteredBlock("red_mushroom_block");
            iron_bars = getRegisteredBlock("iron_bars");
            glass_pane = getRegisteredBlock("glass_pane");
            melon_block = getRegisteredBlock("melon_block");
            pumpkin_stem = getRegisteredBlock("pumpkin_stem");
            melon_stem = getRegisteredBlock("melon_stem");
            vine = getRegisteredBlock("vine");
            oak_fence_gate = getRegisteredBlock("fence_gate");
            spruce_fence_gate = getRegisteredBlock("spruce_fence_gate");
            birch_fence_gate = getRegisteredBlock("birch_fence_gate");
            jungle_fence_gate = getRegisteredBlock("jungle_fence_gate");
            dark_oak_fence_gate = getRegisteredBlock("dark_oak_fence_gate");
            acacia_fence_gate = getRegisteredBlock("acacia_fence_gate");
            brick_stairs = getRegisteredBlock("brick_stairs");
            stone_brick_stairs = getRegisteredBlock("stone_brick_stairs");
            mycelium = (BlockMycelium)getRegisteredBlock("mycelium");
            waterlily = getRegisteredBlock("waterlily");
            nether_brick = getRegisteredBlock("nether_brick");
            nether_brick_fence = getRegisteredBlock("nether_brick_fence");
            nether_brick_stairs = getRegisteredBlock("nether_brick_stairs");
            nether_wart = getRegisteredBlock("nether_wart");
            field_150381_bn = getRegisteredBlock("enchanting_table");
            field_150382_bo = getRegisteredBlock("brewing_stand");
            cauldron = (BlockCauldron)getRegisteredBlock("cauldron");
            end_portal = getRegisteredBlock("end_portal");
            end_portal_frame = getRegisteredBlock("end_portal_frame");
            end_stone = getRegisteredBlock("end_stone");
            dragon_egg = getRegisteredBlock("dragon_egg");
            redstone_lamp = getRegisteredBlock("redstone_lamp");
            lit_redstone_lamp = getRegisteredBlock("lit_redstone_lamp");
            double_wooden_slab = (BlockSlab)getRegisteredBlock("double_wooden_slab");
            wooden_slab = (BlockSlab)getRegisteredBlock("wooden_slab");
            cocoa = getRegisteredBlock("cocoa");
            sandstone_stairs = getRegisteredBlock("sandstone_stairs");
            field_150412_bA = getRegisteredBlock("emerald_ore");
            ender_chest = getRegisteredBlock("ender_chest");
            tripwire_hook = (BlockTripWireHook)getRegisteredBlock("tripwire_hook");
            tripwire = getRegisteredBlock("tripwire");
            emerald_block = getRegisteredBlock("emerald_block");
            spruce_stairs = getRegisteredBlock("spruce_stairs");
            birch_stairs = getRegisteredBlock("birch_stairs");
            jungle_stairs = getRegisteredBlock("jungle_stairs");
            command_block = getRegisteredBlock("command_block");
            field_150461_bJ = (BlockBeacon)getRegisteredBlock("beacon");
            cobblestone_wall = getRegisteredBlock("cobblestone_wall");
            flower_pot = getRegisteredBlock("flower_pot");
            carrots = getRegisteredBlock("carrots");
            potatoes = getRegisteredBlock("potatoes");
            field_150471_bO = getRegisteredBlock("wooden_button");
            skull = (BlockSkull)getRegisteredBlock("skull");
            field_150467_bQ = getRegisteredBlock("anvil");
            field_150447_bR = getRegisteredBlock("trapped_chest");
            light_weighted_pressure_plate = getRegisteredBlock("light_weighted_pressure_plate");
            heavy_weighted_pressure_plate = getRegisteredBlock("heavy_weighted_pressure_plate");
            field_150441_bU = (BlockRedstoneComparator)getRegisteredBlock("unpowered_comparator");
            field_150455_bV = (BlockRedstoneComparator)getRegisteredBlock("powered_comparator");
            field_150453_bW = (BlockDaylightDetector)getRegisteredBlock("daylight_detector");
            field_180402_cm = (BlockDaylightDetector)getRegisteredBlock("daylight_detector_inverted");
            redstone_block = getRegisteredBlock("redstone_block");
            field_150449_bY = getRegisteredBlock("quartz_ore");
            field_150438_bZ = (BlockHopper)getRegisteredBlock("hopper");
            quartz_block = getRegisteredBlock("quartz_block");
            quartz_stairs = getRegisteredBlock("quartz_stairs");
            activator_rail = getRegisteredBlock("activator_rail");
            field_150409_cd = getRegisteredBlock("dropper");
            field_150406_ce = getRegisteredBlock("stained_hardened_clay");
            field_180401_cv = getRegisteredBlock("barrier");
            field_180400_cw = getRegisteredBlock("iron_trapdoor");
            hay_block = getRegisteredBlock("hay_block");
            carpet = getRegisteredBlock("carpet");
            hardened_clay = getRegisteredBlock("hardened_clay");
            coal_block = getRegisteredBlock("coal_block");
            packed_ice = getRegisteredBlock("packed_ice");
            acacia_stairs = getRegisteredBlock("acacia_stairs");
            dark_oak_stairs = getRegisteredBlock("dark_oak_stairs");
            slime_block = getRegisteredBlock("slime");
            double_plant = (BlockDoublePlant)getRegisteredBlock("double_plant");
            field_150399_cn = (BlockStainedGlass)getRegisteredBlock("stained_glass");
            stained_glass_pane = (BlockStainedGlassPane)getRegisteredBlock("stained_glass_pane");
            field_180397_cI = getRegisteredBlock("prismarine");
            sea_lantern = getRegisteredBlock("sea_lantern");
            standing_banner = getRegisteredBlock("standing_banner");
            wall_banner = getRegisteredBlock("wall_banner");
            red_sandstone = getRegisteredBlock("red_sandstone");
            red_sandstone_stairs = getRegisteredBlock("red_sandstone_stairs");
            double_stone_slab2 = (BlockSlab)getRegisteredBlock("double_stone_slab2");
            stone_slab2 = (BlockSlab)getRegisteredBlock("stone_slab2");
        }
    }
}
