package net.minecraft.init;

import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.minecraft.item.ItemArmorStand;
import net.minecraft.item.ItemBow;
import net.minecraft.item.ItemEmptyMap;
import net.minecraft.item.ItemEnchantedBook;
import net.minecraft.item.ItemFishingRod;
import net.minecraft.item.ItemMap;
import net.minecraft.item.ItemPotion;
import net.minecraft.item.ItemShears;
import net.minecraft.util.ResourceLocation;

public class Items
{
    public static final Item iron_shovel;
    public static final Item iron_pickaxe;
    public static final Item iron_axe;
    public static final Item field_151033_d;
    public static final Item apple;
    public static final ItemBow bow;
    public static final Item arrow;
    public static final Item field_151044_h;
    public static final Item field_151045_i;
    public static final Item iron_ingot;
    public static final Item gold_ingot;
    public static final Item field_151040_l;
    public static final Item wooden_sword;
    public static final Item wooden_shovel;
    public static final Item wooden_pickaxe;
    public static final Item wooden_axe;
    public static final Item stone_sword;
    public static final Item stone_shovel;
    public static final Item stone_pickaxe;
    public static final Item stone_axe;
    public static final Item diamond_sword;
    public static final Item diamond_shovel;
    public static final Item field_151046_w;
    public static final Item diamond_axe;
    public static final Item stick;
    public static final Item bowl;
    public static final Item mushroom_stew;
    public static final Item golden_sword;
    public static final Item field_151011_C;
    public static final Item golden_pickaxe;
    public static final Item golden_axe;
    public static final Item field_151007_F;
    public static final Item feather;
    public static final Item gunpowder;
    public static final Item wooden_hoe;
    public static final Item stone_hoe;
    public static final Item iron_hoe;
    public static final Item diamond_hoe;
    public static final Item field_151013_M;
    public static final Item wheat_seeds;
    public static final Item wheat;
    public static final Item bread;
    public static final ItemArmor field_151024_Q;
    public static final ItemArmor leather_chestplate;
    public static final ItemArmor leather_leggings;
    public static final ItemArmor leather_boots;
    public static final ItemArmor chainmail_helmet;
    public static final ItemArmor chainmail_chestplate;
    public static final ItemArmor field_151022_W;
    public static final ItemArmor chainmail_boots;
    public static final ItemArmor iron_helmet;
    public static final ItemArmor iron_chestplate;
    public static final ItemArmor iron_leggings;
    public static final ItemArmor iron_boots;
    public static final ItemArmor diamond_helmet;
    public static final ItemArmor field_151163_ad;
    public static final ItemArmor diamond_leggings;
    public static final ItemArmor field_151175_af;
    public static final ItemArmor golden_helmet;
    public static final ItemArmor golden_chestplate;
    public static final ItemArmor golden_leggings;
    public static final ItemArmor golden_boots;
    public static final Item flint;
    public static final Item porkchop;
    public static final Item cooked_porkchop;
    public static final Item painting;
    public static final Item golden_apple;
    public static final Item sign;
    public static final Item field_179570_aq;
    public static final Item spruce_door;
    public static final Item birch_door;
    public static final Item jungle_door;
    public static final Item acacia_door;
    public static final Item dark_oak_door;
    public static final Item bucket;
    public static final Item field_151131_as;
    public static final Item lava_bucket;
    public static final Item minecart;
    public static final Item saddle;
    public static final Item iron_door;
    public static final Item redstone;
    public static final Item snowball;
    public static final Item boat;
    public static final Item leather;
    public static final Item milk_bucket;
    public static final Item brick;
    public static final Item clay_ball;
    public static final Item reeds;
    public static final Item paper;
    public static final Item book;
    public static final Item slime_ball;
    public static final Item chest_minecart;
    public static final Item furnace_minecart;
    public static final Item egg;
    public static final Item field_151111_aL;
    public static final ItemFishingRod field_151112_aM;
    public static final Item clock;
    public static final Item glowstone_dust;
    public static final Item field_151115_aP;
    public static final Item cooked_fish;
    public static final Item field_151100_aR;
    public static final Item field_151103_aS;
    public static final Item sugar;
    public static final Item field_151105_aU;
    public static final Item bed;
    public static final Item repeater;
    public static final Item cookie;
    public static final ItemMap filled_map;
    public static final ItemShears shears;
    public static final Item melon;
    public static final Item pumpkin_seeds;
    public static final Item melon_seeds;
    public static final Item beef;
    public static final Item cooked_beef;
    public static final Item chicken;
    public static final Item cooked_chicken;
    public static final Item mutton;
    public static final Item cooked_mutton;
    public static final Item rabbit;
    public static final Item cooked_rabbit;
    public static final Item rabbit_stew;
    public static final Item field_179556_br;
    public static final Item rabbit_hide;
    public static final Item field_151078_bh;
    public static final Item field_151079_bi;
    public static final Item blaze_rod;
    public static final Item field_151073_bk;
    public static final Item gold_nugget;
    public static final Item nether_wart;
    public static final ItemPotion potionitem;
    public static final Item glass_bottle;
    public static final Item spider_eye;
    public static final Item fermented_spider_eye;
    public static final Item blaze_powder;
    public static final Item field_151064_bs;
    public static final Item field_151067_bt;
    public static final Item cauldron;
    public static final Item ender_eye;
    public static final Item speckled_melon;
    public static final Item field_151063_bx;
    public static final Item experience_bottle;
    public static final Item fire_charge;
    public static final Item writable_book;
    public static final Item written_book;
    public static final Item emerald;
    public static final Item item_frame;
    public static final Item flower_pot;
    public static final Item carrot;
    public static final Item potato;
    public static final Item baked_potato;
    public static final Item poisonous_potato;
    public static final ItemEmptyMap map;
    public static final Item golden_carrot;
    public static final Item field_151144_bL;
    public static final Item carrot_on_a_stick;
    public static final Item field_151156_bN;
    public static final Item pumpkin_pie;
    public static final Item field_151152_bP;
    public static final Item field_151154_bQ;
    public static final ItemEnchantedBook field_151134_bR;
    public static final Item comparator;
    public static final Item netherbrick;
    public static final Item field_151128_bU;
    public static final Item tnt_minecart;
    public static final Item hopper_minecart;
    public static final ItemArmorStand armor_stand;
    public static final Item iron_horse_armor;
    public static final Item golden_horse_armor;
    public static final Item diamond_horse_armor;
    public static final Item lead;
    public static final Item name_tag;
    public static final Item command_block_minecart;
    public static final Item record_13;
    public static final Item record_cat;
    public static final Item record_blocks;
    public static final Item record_chirp;
    public static final Item record_far;
    public static final Item record_mall;
    public static final Item record_mellohi;
    public static final Item record_stal;
    public static final Item record_strad;
    public static final Item record_ward;
    public static final Item record_11;
    public static final Item record_wait;
    public static final Item prismarine_shard;
    public static final Item field_179563_cD;
    public static final Item banner;

    private static Item getRegisteredItem(String name)
    {
        return (Item)Item.field_150901_e.func_82594_a(new ResourceLocation(name));
    }

    static
    {
        if (!Bootstrap.func_179869_a())
        {
            throw new RuntimeException("Accessed Items before Bootstrap!");
        }
        else
        {
            iron_shovel = getRegisteredItem("iron_shovel");
            iron_pickaxe = getRegisteredItem("iron_pickaxe");
            iron_axe = getRegisteredItem("iron_axe");
            field_151033_d = getRegisteredItem("flint_and_steel");
            apple = getRegisteredItem("apple");
            bow = (ItemBow)getRegisteredItem("bow");
            arrow = getRegisteredItem("arrow");
            field_151044_h = getRegisteredItem("coal");
            field_151045_i = getRegisteredItem("diamond");
            iron_ingot = getRegisteredItem("iron_ingot");
            gold_ingot = getRegisteredItem("gold_ingot");
            field_151040_l = getRegisteredItem("iron_sword");
            wooden_sword = getRegisteredItem("wooden_sword");
            wooden_shovel = getRegisteredItem("wooden_shovel");
            wooden_pickaxe = getRegisteredItem("wooden_pickaxe");
            wooden_axe = getRegisteredItem("wooden_axe");
            stone_sword = getRegisteredItem("stone_sword");
            stone_shovel = getRegisteredItem("stone_shovel");
            stone_pickaxe = getRegisteredItem("stone_pickaxe");
            stone_axe = getRegisteredItem("stone_axe");
            diamond_sword = getRegisteredItem("diamond_sword");
            diamond_shovel = getRegisteredItem("diamond_shovel");
            field_151046_w = getRegisteredItem("diamond_pickaxe");
            diamond_axe = getRegisteredItem("diamond_axe");
            stick = getRegisteredItem("stick");
            bowl = getRegisteredItem("bowl");
            mushroom_stew = getRegisteredItem("mushroom_stew");
            golden_sword = getRegisteredItem("golden_sword");
            field_151011_C = getRegisteredItem("golden_shovel");
            golden_pickaxe = getRegisteredItem("golden_pickaxe");
            golden_axe = getRegisteredItem("golden_axe");
            field_151007_F = getRegisteredItem("string");
            feather = getRegisteredItem("feather");
            gunpowder = getRegisteredItem("gunpowder");
            wooden_hoe = getRegisteredItem("wooden_hoe");
            stone_hoe = getRegisteredItem("stone_hoe");
            iron_hoe = getRegisteredItem("iron_hoe");
            diamond_hoe = getRegisteredItem("diamond_hoe");
            field_151013_M = getRegisteredItem("golden_hoe");
            wheat_seeds = getRegisteredItem("wheat_seeds");
            wheat = getRegisteredItem("wheat");
            bread = getRegisteredItem("bread");
            field_151024_Q = (ItemArmor)getRegisteredItem("leather_helmet");
            leather_chestplate = (ItemArmor)getRegisteredItem("leather_chestplate");
            leather_leggings = (ItemArmor)getRegisteredItem("leather_leggings");
            leather_boots = (ItemArmor)getRegisteredItem("leather_boots");
            chainmail_helmet = (ItemArmor)getRegisteredItem("chainmail_helmet");
            chainmail_chestplate = (ItemArmor)getRegisteredItem("chainmail_chestplate");
            field_151022_W = (ItemArmor)getRegisteredItem("chainmail_leggings");
            chainmail_boots = (ItemArmor)getRegisteredItem("chainmail_boots");
            iron_helmet = (ItemArmor)getRegisteredItem("iron_helmet");
            iron_chestplate = (ItemArmor)getRegisteredItem("iron_chestplate");
            iron_leggings = (ItemArmor)getRegisteredItem("iron_leggings");
            iron_boots = (ItemArmor)getRegisteredItem("iron_boots");
            diamond_helmet = (ItemArmor)getRegisteredItem("diamond_helmet");
            field_151163_ad = (ItemArmor)getRegisteredItem("diamond_chestplate");
            diamond_leggings = (ItemArmor)getRegisteredItem("diamond_leggings");
            field_151175_af = (ItemArmor)getRegisteredItem("diamond_boots");
            golden_helmet = (ItemArmor)getRegisteredItem("golden_helmet");
            golden_chestplate = (ItemArmor)getRegisteredItem("golden_chestplate");
            golden_leggings = (ItemArmor)getRegisteredItem("golden_leggings");
            golden_boots = (ItemArmor)getRegisteredItem("golden_boots");
            flint = getRegisteredItem("flint");
            porkchop = getRegisteredItem("porkchop");
            cooked_porkchop = getRegisteredItem("cooked_porkchop");
            painting = getRegisteredItem("painting");
            golden_apple = getRegisteredItem("golden_apple");
            sign = getRegisteredItem("sign");
            field_179570_aq = getRegisteredItem("wooden_door");
            spruce_door = getRegisteredItem("spruce_door");
            birch_door = getRegisteredItem("birch_door");
            jungle_door = getRegisteredItem("jungle_door");
            acacia_door = getRegisteredItem("acacia_door");
            dark_oak_door = getRegisteredItem("dark_oak_door");
            bucket = getRegisteredItem("bucket");
            field_151131_as = getRegisteredItem("water_bucket");
            lava_bucket = getRegisteredItem("lava_bucket");
            minecart = getRegisteredItem("minecart");
            saddle = getRegisteredItem("saddle");
            iron_door = getRegisteredItem("iron_door");
            redstone = getRegisteredItem("redstone");
            snowball = getRegisteredItem("snowball");
            boat = getRegisteredItem("boat");
            leather = getRegisteredItem("leather");
            milk_bucket = getRegisteredItem("milk_bucket");
            brick = getRegisteredItem("brick");
            clay_ball = getRegisteredItem("clay_ball");
            reeds = getRegisteredItem("reeds");
            paper = getRegisteredItem("paper");
            book = getRegisteredItem("book");
            slime_ball = getRegisteredItem("slime_ball");
            chest_minecart = getRegisteredItem("chest_minecart");
            furnace_minecart = getRegisteredItem("furnace_minecart");
            egg = getRegisteredItem("egg");
            field_151111_aL = getRegisteredItem("compass");
            field_151112_aM = (ItemFishingRod)getRegisteredItem("fishing_rod");
            clock = getRegisteredItem("clock");
            glowstone_dust = getRegisteredItem("glowstone_dust");
            field_151115_aP = getRegisteredItem("fish");
            cooked_fish = getRegisteredItem("cooked_fish");
            field_151100_aR = getRegisteredItem("dye");
            field_151103_aS = getRegisteredItem("bone");
            sugar = getRegisteredItem("sugar");
            field_151105_aU = getRegisteredItem("cake");
            bed = getRegisteredItem("bed");
            repeater = getRegisteredItem("repeater");
            cookie = getRegisteredItem("cookie");
            filled_map = (ItemMap)getRegisteredItem("filled_map");
            shears = (ItemShears)getRegisteredItem("shears");
            melon = getRegisteredItem("melon");
            pumpkin_seeds = getRegisteredItem("pumpkin_seeds");
            melon_seeds = getRegisteredItem("melon_seeds");
            beef = getRegisteredItem("beef");
            cooked_beef = getRegisteredItem("cooked_beef");
            chicken = getRegisteredItem("chicken");
            cooked_chicken = getRegisteredItem("cooked_chicken");
            mutton = getRegisteredItem("mutton");
            cooked_mutton = getRegisteredItem("cooked_mutton");
            rabbit = getRegisteredItem("rabbit");
            cooked_rabbit = getRegisteredItem("cooked_rabbit");
            rabbit_stew = getRegisteredItem("rabbit_stew");
            field_179556_br = getRegisteredItem("rabbit_foot");
            rabbit_hide = getRegisteredItem("rabbit_hide");
            field_151078_bh = getRegisteredItem("rotten_flesh");
            field_151079_bi = getRegisteredItem("ender_pearl");
            blaze_rod = getRegisteredItem("blaze_rod");
            field_151073_bk = getRegisteredItem("ghast_tear");
            gold_nugget = getRegisteredItem("gold_nugget");
            nether_wart = getRegisteredItem("nether_wart");
            potionitem = (ItemPotion)getRegisteredItem("potion");
            glass_bottle = getRegisteredItem("glass_bottle");
            spider_eye = getRegisteredItem("spider_eye");
            fermented_spider_eye = getRegisteredItem("fermented_spider_eye");
            blaze_powder = getRegisteredItem("blaze_powder");
            field_151064_bs = getRegisteredItem("magma_cream");
            field_151067_bt = getRegisteredItem("brewing_stand");
            cauldron = getRegisteredItem("cauldron");
            ender_eye = getRegisteredItem("ender_eye");
            speckled_melon = getRegisteredItem("speckled_melon");
            field_151063_bx = getRegisteredItem("spawn_egg");
            experience_bottle = getRegisteredItem("experience_bottle");
            fire_charge = getRegisteredItem("fire_charge");
            writable_book = getRegisteredItem("writable_book");
            written_book = getRegisteredItem("written_book");
            emerald = getRegisteredItem("emerald");
            item_frame = getRegisteredItem("item_frame");
            flower_pot = getRegisteredItem("flower_pot");
            carrot = getRegisteredItem("carrot");
            potato = getRegisteredItem("potato");
            baked_potato = getRegisteredItem("baked_potato");
            poisonous_potato = getRegisteredItem("poisonous_potato");
            map = (ItemEmptyMap)getRegisteredItem("map");
            golden_carrot = getRegisteredItem("golden_carrot");
            field_151144_bL = getRegisteredItem("skull");
            carrot_on_a_stick = getRegisteredItem("carrot_on_a_stick");
            field_151156_bN = getRegisteredItem("nether_star");
            pumpkin_pie = getRegisteredItem("pumpkin_pie");
            field_151152_bP = getRegisteredItem("fireworks");
            field_151154_bQ = getRegisteredItem("firework_charge");
            field_151134_bR = (ItemEnchantedBook)getRegisteredItem("enchanted_book");
            comparator = getRegisteredItem("comparator");
            netherbrick = getRegisteredItem("netherbrick");
            field_151128_bU = getRegisteredItem("quartz");
            tnt_minecart = getRegisteredItem("tnt_minecart");
            hopper_minecart = getRegisteredItem("hopper_minecart");
            armor_stand = (ItemArmorStand)getRegisteredItem("armor_stand");
            iron_horse_armor = getRegisteredItem("iron_horse_armor");
            golden_horse_armor = getRegisteredItem("golden_horse_armor");
            diamond_horse_armor = getRegisteredItem("diamond_horse_armor");
            lead = getRegisteredItem("lead");
            name_tag = getRegisteredItem("name_tag");
            command_block_minecart = getRegisteredItem("command_block_minecart");
            record_13 = getRegisteredItem("record_13");
            record_cat = getRegisteredItem("record_cat");
            record_blocks = getRegisteredItem("record_blocks");
            record_chirp = getRegisteredItem("record_chirp");
            record_far = getRegisteredItem("record_far");
            record_mall = getRegisteredItem("record_mall");
            record_mellohi = getRegisteredItem("record_mellohi");
            record_stal = getRegisteredItem("record_stal");
            record_strad = getRegisteredItem("record_strad");
            record_ward = getRegisteredItem("record_ward");
            record_11 = getRegisteredItem("record_11");
            record_wait = getRegisteredItem("record_wait");
            prismarine_shard = getRegisteredItem("prismarine_shard");
            field_179563_cD = getRegisteredItem("prismarine_crystals");
            banner = getRegisteredItem("banner");
        }
    }
}
